### ISSUE TITLE
Addon removed from addons.mozilla.org

### ISSUE THREAD

**Issue by BubiBalboa** [afk-mcz/busca#15]
Why is your addon no longer available?

**Comment by afk-mario** [comment]
Hey didn't saw this, it was removed because I didn't provide a un-ofuscated version of the source code on the submission, about to re-submit again

**Comment by BubiBalboa** [comment]
I wanted to recommend your addon in a thread and link it and was surprised to see it wasn't there anymore. 

Glad to hear it isn't gone for good!

**Comment by afk-mario** [comment]
Re-submited! Finally had some time to add some things, next-up will be sorting by date and comments

**Comment by BubiBalboa** [comment]
Awesome! I love updates!

**Comment by afk-mario** [comment]
It's available again
