### ISSUE TITLE
Horizontal scroll bars on the pop up window

### ISSUE THREAD

**Issue by BubiBalboa** [afk-mcz/busca#7]
I think it only happens when there are so many results that the vertical scroll bars appear.
![2017-12-20 11_20_08-](https://user-images.githubusercontent.com/8809532/34202427-05b792be-e578-11e7-8563-15f727e74c2c.png)
![2017-12-20 11_21_05-](https://user-images.githubusercontent.com/8809532/34202434-082d1b68-e578-11e7-8b7f-c3df3cbb2037.png)

I have seen addons where the settings dialogue was affected by the page zoom factor but this isn't the case here.

**Comment by afk-mario** [comment]
I pushed a new version attempting to solve this issue, on my Mac scroll bars don't appear so I'm not sure if it's fixed, let me know

**Comment by BubiBalboa** [comment]
Works. You're fast!

Is it possible to theme the scroll bars? The standard ones look a bit odd with the dark theme.

**Comment by afk-mario** [comment]
I will try, honestly I prefer to hide them, but it may be weird for some people.
